### ISSUE TITLE
 Noob question: How to disarm/home/away?

### ISSUE THREAD

**Issue by qnguye** [homespun/ring-alarm#4]
I ran the test.js but can’t figure out how to set those mode

**Comment by acolytec3** [comment]
The test.js doesn't set the alarm mode.  It just connects to the API, pulls all the alarm devices, and then sets up a call back on the status update message.  Per the documentation, add a function call inside your ring.stations{} call that looks something like this: 
```
ring.stations(err, stations) => {
   ring.setAlarmMot hde(stations[0], panelId, 'away', [] (err, station, message) => {}
  });
```

To get the panelId, run the test.js and look for the alarm-device that has a device type of "security panel" that will get printed out in the logs.  Grab the device ID for that device and then put that in the panelId field noted above.  This will set the alarm to away.  Replace "away' with 'some' if you want to mimic the "home" setting in the Ring Alarm app or "none" to turn it off.

**Comment by qnguye** [comment]
This is what i got and don't see id for panel. Perhaps, none device found

`station={
  "id": [hidden],
  "description": "Alarm Base Station",
  "device_id": "[hidden]",
  "time_zone": "America/Los_Angeles",
  "kind": "base_station_v1",
  "stolen": false,
  "owned": true,
  "settings": null,
  "latitude": [hidden],
  "longitude": [hidden],
  "address": "[hidden]",
  "alerts": [],
  "features": null,
  "location_id": "[hidden]",
  "ring_id": null,
  "firmware_version": "Up to Date",
  "owner": {
    "id": [hidden],
    "email": "[hidden]",
    "first_name": "[hidden]",
    "last_name": "[hidden]"
  }
}
getAlarmDevices: errP=false station=[hidden]
deviceType=adapter.zigbee
deviceType=access-code.vault
deviceType=security-panel
deviceType=access-code
deviceType=hub.redsky
deviceType=adapter.zwave
deviceType=range-extender.zwave
deviceType=security-keypad
{
  "deviceType": "SecuritySystem",
  "deviceId": "[hidden]",
  "manufacturer": "Ring",
  "model": "base_station_v1",
  "name": "Ring Keypad [hidden]",
  "serialNumber": "[hidden]",
  "firmwareRevision": "1.8.0 (30)",
  "statusActive": true,
  "securitySystemAlarmType": "TBD: 0(alarm conditions are cleared) OR 1(alarm type not known)",
  "devices": [
    {
      "deviceType": "ContactSensor",
      "deviceId": "[hidden]",
      "manufacturer": "Ring",
      "model": "sensor.contact",
      "name": "Dining Room Window Left",
      "serialNumber": "[hidden]",
      "firmwareRevision": "838.513.513",
      "statusActive": true,
      "contactSensorState": "DETECTED",
      "statusTampered": "NOT_TAMPERED",
      "statusLowBattery": false,
      "polling": {
        "nextExpectedWakeup": 1545476281366,
        "pollInterval": 43200000
      }
    },
    ....and my other contact sensor[hidden]
  ],
  "securitySystemTargetState": "DISARMED",
  "securitySystemCrrentState": "DISARMED",
  "statusTampered": "NOT_TAMPERED"
}
`

**Comment by acolytec3** [comment]
If you drop the below snippet or something similar into the target function where the getAlarmDevices call is made in the test.js script, do you not see a device with device type listed as security-panel?  There should be one if you have a ring alarm system (at least, one shows up in mine).  You use the zid associated with that device to control the alarm using the setAlarmMode command referenced in my earlier post.

`message.body.forEach((device) => {console.log("device type= "+ device.general.v2.deviceType + " with device ID= " + device.general.v2.zid)});`
