### ISSUE TITLE
Current system status

### ISSUE THREAD

**Issue by mangvlad** [homespun/ring-alarm#6]
What is the easiest/documented way to figure out current system mode (armed home/armed away/disarmed)?

Thanks!

**Comment by joeyberkovitz** [comment]
See https://github.com/homespun/ring-alarm/blob/64ad809409eb776470a7263e73a9c3deea361294/test.js#L64-L67

If you call getAlarmDevices() and loop through the devices, the one that has the mode property will tell you what mode the alarm is in.
